// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct response_login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static response_login GetRootAsresponse_login(ByteBuffer _bb) { return GetRootAsresponse_login(_bb, new response_login()); }
  public static response_login GetRootAsresponse_login(ByteBuffer _bb, response_login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public response_login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ErrorCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<packet.response_login> Createresponse_login(FlatBufferBuilder builder,
      int error_code = 0) {
    builder.StartTable(1);
    response_login.AddErrorCode(builder, error_code);
    return response_login.Endresponse_login(builder);
  }

  public static void Startresponse_login(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, int errorCode) { builder.AddInt(0, errorCode, 0); }
  public static Offset<packet.response_login> Endresponse_login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<packet.response_login>(o);
  }
}


}
