// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum id : int
{
  PING = 0,
  PONG = 1,
  ESTABLISH = 2,
  LOGIN_REQUEST = 2001,
  LOGIN_RESPONSE = 2002,
};


}
